export const PRODUCTIVITY_ERROR_CODES = {
  THINGS_UNAVAILABLE: 'THINGS_UNAVAILABLE',
  THINGS_PERMISSION_DENIED: 'THINGS_PERMISSION_DENIED',
  FEISHU_UNAUTHORIZED: 'FEISHU_UNAUTHORIZED',
  FEISHU_SCOPE_LIMITED: 'FEISHU_SCOPE_LIMITED',
  CALENDAR_PERMISSION_DENIED: 'CALENDAR_PERMISSION_DENIED',
  CALENDAR_WRITE_ONLY: 'CALENDAR_WRITE_ONLY',
  CALENDAR_HELPER_STALE: 'CALENDAR_HELPER_STALE',
  CALENDAR_NEEDS_RECONNECT: 'CALENDAR_NEEDS_RECONNECT',
  CALENDAR_CONFLICT: 'CALENDAR_CONFLICT',
  SYNC_IN_PROGRESS: 'SYNC_IN_PROGRESS',
  DUPLICATE_SOURCE_ITEM: 'DUPLICATE_SOURCE_ITEM',
  NO_AVAILABLE_SLOT: 'NO_AVAILABLE_SLOT',
  EXTERNAL_WRITE_DISABLED: 'EXTERNAL_WRITE_DISABLED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_TIMEOUT: 'AI_TIMEOUT',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_BUDGET_EXHAUSTED: 'AI_BUDGET_EXHAUSTED',
  AI_SCHEMA_INVALID: 'AI_SCHEMA_INVALID',
  CALENDAR_BUSY_UNKNOWN: 'CALENDAR_BUSY_UNKNOWN',
  SETTINGS_REJECTED: 'SETTINGS_REJECTED',
  SCHEMA_MIGRATION_FAILED: 'SCHEMA_MIGRATION_FAILED',
  CLIENT_EVIDENCE_REJECTED: 'CLIENT_EVIDENCE_REJECTED',
  TODO_READONLY: 'TODO_READONLY',
  TODO_NOT_SCHEDULABLE: 'TODO_NOT_SCHEDULABLE',
  AGENDA_COVERAGE: 'AGENDA_COVERAGE',
  DLP_BLOCKED: 'DLP_BLOCKED',
  AI_LIVE_DISABLED: 'AI_LIVE_DISABLED',
} as const;

export type ProductivityErrorCode = (typeof PRODUCTIVITY_ERROR_CODES)[keyof typeof PRODUCTIVITY_ERROR_CODES];

const STATUS_BY_CODE: Record<ProductivityErrorCode, number> = {
  VALIDATION_ERROR: 400,
  SETTINGS_REJECTED: 400,
  AI_SCHEMA_INVALID: 400,
  FEISHU_UNAUTHORIZED: 401,
  THINGS_PERMISSION_DENIED: 403,
  FEISHU_SCOPE_LIMITED: 403,
  CALENDAR_PERMISSION_DENIED: 403,
  CALENDAR_WRITE_ONLY: 403,
  CALENDAR_HELPER_STALE: 503,
  CALENDAR_NEEDS_RECONNECT: 409,
  EXTERNAL_WRITE_DISABLED: 403,
  DUPLICATE_SOURCE_ITEM: 409,
  CALENDAR_CONFLICT: 409,
  SYNC_IN_PROGRESS: 409,
  THINGS_UNAVAILABLE: 503,
  NO_AVAILABLE_SLOT: 503,
  AI_NOT_CONFIGURED: 503,
  AI_UNAVAILABLE: 503,
  AI_TIMEOUT: 504,
  AI_RATE_LIMITED: 429,
  AI_BUDGET_EXHAUSTED: 503,
  CALENDAR_BUSY_UNKNOWN: 503,
  SCHEMA_MIGRATION_FAILED: 500,
  CLIENT_EVIDENCE_REJECTED: 422,
  TODO_READONLY: 403,
  TODO_NOT_SCHEDULABLE: 422,
  AGENDA_COVERAGE: 409,
  DLP_BLOCKED: 422,
  AI_LIVE_DISABLED: 403,
};

export class ProductivityError extends Error {
  readonly code: ProductivityErrorCode;
  readonly httpStatus: number;
  readonly details: Record<string, unknown>;

  constructor(code: ProductivityErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(message);
    this.name = 'ProductivityError';
    this.code = code;
    this.httpStatus = STATUS_BY_CODE[code] ?? 500;
    this.details = details;
  }
}

export function mapProductivityError(err: unknown): { status: number; code: string; message: string; details?: Record<string, unknown> } {
  if (err instanceof ProductivityError) {
    return { status: err.httpStatus, code: err.code, message: err.message, details: err.details };
  }
  const message = err instanceof Error ? err.message : '未知错误';
  return { status: 500, code: 'INTERNAL_ERROR', message };
}
